[sssd]
services = nss, pam, ssh, sudo
domains = devuatprod.com

[nss]
filter_users = root, nobody

[pam]
offline_credentials_expiration = 1
offline_failed_login_attempts = 2
offline_failed_login_delay = 10
pam_verbosity = 1

[domain/devuatprod.com]
id_provider = ipa
auth_provider = ipa
access_provider = ipa
chpass_provider = ipa

ipa_domain = devuatprod.com
ipa_server = ipa.devuatprod.com
ipa_hostname = _HOSTNAME_

ldap_tls_cacert = /etc/ipa/ca.crt

autofs_provider = ipa

cache_credentials = true
krb5_store_password_if_offline = true

ipa_automount_location = default
selinux_provider = ipa

# PROD: Key + password + OTP (keyboard-interactive)
# pam_verbosity=1 enables separate Password: and OTP: prompts
pam_verbosity = 1