[sssd]
services = nss, pam, ssh
domains = devuatprod.com

[nss]
filter_users = root, nobody

[pam]
offline_credentials_expiration = 2
offline_failed_login_attempts = 3
offline_failed_login_delay = 5

[domain/devuatprod.com]
id_provider = ipa
auth_provider = ipa
access_provider = ipa
chpass_provider = ipa

ipa_domain = devuatprod.com
ipa_server = ipa.devuatprod.com
ipa_hostname = _HOSTNAME_

ldap_tls_cacert = /etc/ipa/ca.crt

autofs_provider = ipa

cache_credentials = true
krb5_store_password_if_offline = false

ipa_automount_location = default
selinux_provider = ipa

# DEV: Key-only auth
# SSH public key is the sole authentication method
pam_verbosity = 0