[sssd]
services = nss, pam, ssh
domains = test.local

[nss]
filter_users = root, nobody

[pam]
offline_credentials_expiration = 2
offline_failed_login_attempts = 3
offline_failed_login_delay = 5

[domain/test.local]
id_provider = ipa
auth_provider = ipa
access_provider = ipa
chpass_provider = ipa
ipa_domain = test.local
ipa_server = ipa.test.local
ldap_tls_cacert = /etc/ipa/ca.crt
autofs_provider = ipa
cache_credentials = true
krb5_store_password_if_offline = true
ipa_automount_location = default
selinux_provider = none
pam_verbosity = 0
